name: Kernel-Build

on:
  workflow_dispatch:
  watch:
    types: [started]

env:
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  TELEGRAM_CHAT: -1001655956753

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: himemori/archlinux:latest
    steps:
        - uses: actions/checkout@v3.0.2
        - name: Build
          run: |
           git clone --depth=1 https://github.com/Himemoria/android_kernel_xiaomi_mt6768 kernel -b twelve
           cd kernel
           wget https://raw.githubusercontent.com/Himemoria/Scripts/main/kernel-build.sh >/dev/null
           bash kernel-build.sh clang full-lto
